experiment_name: "ijepa/mini_imagenet"
method_type: "ijepa"

dataset:
  name: "mini_imagenet"
  path: "./data/"
  num_output_classes: 100 

model:
  encoder_type: "vit_h"
  pretrained: True
  context_encoder_depth: 12
  target_encoder_depth: 12
  predictor_depth: 6
  embed_dim: 768
  ema_momentum: 0.996
  image_size: 224
  patch_size: 14

evaluation:
  checkpoints_dir: "./"
  perform_cdnv: True
  perform_nccc: True
  perform_linear: True

linear:
  batch_size: 256
  num_epochs: 100  
  num_output_classes: 100  
  augment_both: False
  top_lr: 3e-4
  momentum: 0.9
  weight_decay: 5e-4
  track_performance: True
  save_every: 10